import type { ValidationRule } from '../../types/guaranteeLetter'
import { Icon } from '../Icon'

type Props = { isValidating: boolean; rules: ValidationRule[]; documentReady: boolean }

export function AiReviewPanel({ isValidating, rules, documentReady }: Props) {
  const completeCount = rules.filter(rule => rule.complete).length
  return <section className="rounded-xl border border-[#c3c6d6] bg-white shadow-sm"><div className="border-b border-[#dce2f3] p-5"><div className="flex items-start justify-between gap-4"><div><p className="flex items-center gap-1.5 text-xs font-bold uppercase tracking-[.08em] text-[#003d9b]"><Icon name="sparkles" className="h-4 w-4" />AI validation</p><h2 className="mt-2 text-lg font-semibold">GL package readiness</h2></div><span className={`grid h-10 w-10 place-items-center rounded-full ${isValidating ? 'bg-amber-50 text-amber-700' : documentReady ? 'bg-emerald-50 text-emerald-700' : 'bg-[#f0f3ff] text-[#555f6c]'}`}><Icon name={isValidating ? 'refresh' : documentReady ? 'check' : 'sparkles'} className={`h-5 w-5 ${isValidating ? 'animate-spin' : ''}`} /></span></div><p className="mt-3 text-sm leading-5 text-[#555f6c]">{isValidating ? 'Reading the admission note and checking policy rules…' : documentReady ? `${completeCount} of ${rules.length} requirements verified.` : 'Upload the doctor’s note to begin the pre-submission check.'}</p></div><div className="space-y-3 p-5">{rules.map(rule => <div key={rule.id} className="flex gap-3"><span className={`mt-0.5 grid h-5 w-5 shrink-0 place-items-center rounded-full ${rule.complete ? 'bg-emerald-100 text-emerald-700' : 'bg-[#dce2f3] text-[#555f6c]'}`}><Icon name={rule.complete ? 'check' : 'close'} className="h-3 w-3" /></span><div><p className="text-sm font-semibold text-[#151c27]">{rule.label}</p><p className="mt-0.5 text-xs leading-4 text-[#555f6c]">{rule.detail}</p></div></div>)}</div>{documentReady && <div className="mx-5 mb-5 rounded-lg bg-[#f0f3ff] p-3"><p className="text-xs font-bold text-[#003d9b]">AI summary</p><p className="mt-1 text-xs leading-5 text-[#434654]">Acute gastroenteritis (ICD-10 A09) detected. Estimated cost MYR 6,400 is within the patient’s remaining annual limit.</p></div>}</section>
}
